/// Flutter icons LostArk
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  LostArk
///      fonts:
///       - asset: fonts/LostArk.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class LostArk {
  LostArk._();

  static const _kFontFam = 'LostArk';

  static const IconData class_arcana = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData class_bard = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData class_battlemaster = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData class_berserker = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData class_blaster = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData class_destroyer = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData class_devilhunter = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData class_fighter = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData class_hawkeye = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData class_hunter = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData class_infighter = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData class_magician = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData class_soulmaster = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData class_summoner = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData class_warlord = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData class_warrior = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData logo = const IconData(0xe810, fontFamily: _kFontFam);
}
