/// Flutter icons LostArk
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  LostArk
///      fonts:
///       - asset: fonts/LostArk.ttf
///
///
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class LostArk {
  LostArk._();

  static const _kFontFam = 'LostArk';

  static Map<String, IconData> icons = {
    'class_arcana': class_arcana,
    'class_bard': class_bard,
    'class_battlemaster': class_battlemaster,
    'class_berserker': class_berserker,
    'class_blaster': class_blaster,
    'class_destroyer': class_destroyer,
    'class_devilhunter': class_devilhunter,
    'class_fighter': class_fighter,
    'class_hawkeye': class_hawkeye,
    'class_hunter': class_hunter,
    'class_infighter': class_infighter,
    'class_magician': class_magician,
    'class_soulmaster': class_soulmaster,
    'class_summoner': class_summoner,
    'class_warlord': class_warlord,
    'class_warrior': class_warrior,
    'class_lancemaster': class_lancemaster,
    'class_blade': class_blade,
    'class_demonic': class_demonic,
    'logo': logo,
    'down': down,
    'social_youtube': social_youtube,
    'up': up,
    'hourglass': hourglass,
    'download': download,
    'upload': upload,
    'comment': comment,
    'cog_alt': cog_alt,
    'reddit_squared': reddit_squared,
    'reddit_alien': reddit_alien,
  };

  static const IconData class_arcana =
      const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData class_bard =
      const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData class_battlemaster =
      const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData class_berserker =
      const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData class_blaster =
      const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData class_destroyer =
      const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData class_devilhunter =
      const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData class_fighter =
      const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData class_hawkeye =
      const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData class_hunter =
      const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData class_infighter =
      const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData class_magician =
      const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData class_soulmaster =
      const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData class_summoner =
      const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData class_warlord =
      const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData class_warrior =
      const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData class_lancemaster =
      const IconData(0xf113, fontFamily: _kFontFam);
  static const IconData class_blade = const IconData(0xf10d, fontFamily: _kFontFam);
  static const IconData class_demonic = const IconData(0xf10f, fontFamily: _kFontFam);
  static const IconData logo = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData down = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData social_youtube =
      const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData up = const IconData(0xe817, fontFamily: _kFontFam);
  static const IconData hourglass =
      const IconData(0xe819, fontFamily: _kFontFam);
  static const IconData download =
      const IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData upload = const IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData comment = const IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData cog_alt = const IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData reddit_squared =
      const IconData(0xf1a2, fontFamily: _kFontFam);
  static const IconData reddit_alien =
      const IconData(0xf281, fontFamily: _kFontFam);
}
