name: lost_ark
description: A new Flutter project.
version: 1.1.2+7

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
 
  auto_size_text: ^2.1.0
  cupertino_icons: ^0.1.3
  flutter_cupertino_localizations: ^1.0.1
  html_unescape: ^1.0.1+3
  http: ^0.12.1
  intl: ^0.16.0
  path_provider: ^1.6.9
  provider: ^4.1.2
  sembast: ^2.4.4+1
  shared_preferences: ^0.5.7+3
  webview_flutter: ^0.3.22+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
   - assets/lang/
   - assets/data/
   - assets/img/
   - assets/icons/tripod/
   - assets/icons/arcana/
   - assets/icons/bard/
   - assets/icons/battlemaster/
   - assets/icons/berserker/
   - assets/icons/blade/
   - assets/icons/blaster/
   - assets/icons/demonic/
   - assets/icons/destroyer/
   - assets/icons/devilhunter/
   - assets/icons/hawkeye/
   - assets/icons/infighter/
   - assets/icons/lancemaster/
   - assets/icons/soulmaster/
   - assets/icons/summoner/
   - assets/icons/warlord/
  fonts:
    - family: LostArk
      fonts:
        - asset: fonts/LostArk.ttf
    - family: Alegreya
      fonts:
        - asset: fonts/AlegreyaSansSC-Regular.ttf