name: lost_ark
description: A new Flutter project.
version: 1.2.0+10

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
 
  auto_size_text: 3.0.0
  cupertino_icons: 1.0.4
  flutter_cupertino_localizations: 1.0.1
  html_unescape: 2.0.0
  http: 0.13.4
  intl: 0.17.0
  lint: 1.8.2
  path: 1.8.0
  path_provider: 2.0.8
  provider: 6.0.2
  sembast: 3.1.1+1
  shared_preferences: 2.0.11
  webview_flutter: 3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
   - assets/lang/
   - assets/data/
   - assets/img/
   - assets/icons/tripod/
   - assets/icons/arcana/
   - assets/icons/bard/
   - assets/icons/wardancer/
   - assets/icons/berserker/
   - assets/icons/deathblade/
   - assets/icons/artillerist/
   - assets/icons/shadowhunter/
   - assets/icons/destroyer/
   - assets/icons/deadeye/
   - assets/icons/sharpshooter/
   - assets/icons/scrapper/
   - assets/icons/lancemaster/
   - assets/icons/soulfist/
   - assets/icons/summoner/
   - assets/icons/gunlancer/
  fonts:
    - family: LostArk
      fonts:
        - asset: fonts/LostArk.ttf
    - family: Alegreya
      fonts:
        - asset: fonts/AlegreyaSansSC-Regular.ttf