name: lost_ark
description: A new Flutter project.
version: 1.2.0+9

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
 
  auto_size_text: 2.1.0
  cupertino_icons: 1.0.0
  flutter_cupertino_localizations: 1.0.1
  html_unescape: 1.0.2
  http: 0.12.2
  intl: 0.16.1
  path_provider: 1.6.28
  provider: 4.3.3
  sembast: 2.4.10+4
  shared_preferences: 0.5.12+4
  webview_flutter: 1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
   - assets/lang/
   - assets/data/
   - assets/img/
   - assets/icons/tripod/
   - assets/icons/arcana/
   - assets/icons/bard/
   - assets/icons/battlemaster/
   - assets/icons/berserker/
   - assets/icons/blade/
   - assets/icons/blaster/
   - assets/icons/demonic/
   - assets/icons/destroyer/
   - assets/icons/devilhunter/
   - assets/icons/hawkeye/
   - assets/icons/infighter/
   - assets/icons/lancemaster/
   - assets/icons/soulmaster/
   - assets/icons/summoner/
   - assets/icons/warlord/
  fonts:
    - family: LostArk
      fonts:
        - asset: fonts/LostArk.ttf
    - family: Alegreya
      fonts:
        - asset: fonts/AlegreyaSansSC-Regular.ttf